name: Build and Push Backend Docker Image

on:
  push:
    branches:
      - main # Or master
  # Optional: trigger on tags like v1.0 to create versioned images
  # tags:
  #   - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub (or ghcr.io)
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Set these secrets in repo settings
        password: ${{ secrets.DOCKER_PASSWORD }} # Set these secrets in repo settings
        # Or for ghcr.io:
        # registry: ghcr.io
        # username: ${{ github.actor }}
        # password: ${{ secrets.GITHUB_TOKEN }} # Use the built-in token for ghcr.io

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./backend # Point Docker to the backend directory
        push: true
        tags: your_dockerhub_username/pothole-detector-backend:latest # Replace with your Docker Hub username
        # Or for ghcr.io:
        # tags: ghcr.io/${{ github.repository }}/backend:latest # Use ghcr.io naming convention